### PR TITLE
exam bank ux

### PR DESCRIPTION
**Pull request by jazlynnL**
changed titles of buttons and disabled upload button until exams have been added.

I can't figure out how to change the colour of the button though, I wanted it grey by default and then pink after exams were added but not that familiar w react :(

### CODE REVIEW

**Review by some-molasses — APPROVED** [review]
looks good!

**Comment by Andoiiii** [comment]
I'm just gonna add onto this branch. I think i got it working?
image
image

wondering if there could be a better color choice. Maybe invert the text too when its greyed out?

**Comment by some-molasses** [comment]
@Andoiiii haha yeah I think I agree with your assessment that there has to be a better colour 😅 

can we make it something darker? Accessibility guidelines ([1.4.3 text elements](https://www.w3.org/TR/WCAG21/#contrast-minimum), [1.4.11 non-text elements](https://www.w3.org/TR/WCAG21/#non-text-contrast)) state that we should have both the button and the text within it stand out from their surroundings. A darker grey would probably do it?

**Comment by Andoiiii** [comment]
@some-molasses true, how about this? THis is mathsoc-grey-2
image

**Review by some-molasses — APPROVED** [review]
yeah that looks a lot better!

**Pull request merged**
