### PR TITLE
Refactor server directory structure

### PR DESCRIPTION
**Pull request by ad-world**
Lots of files were moved and deleted. This basically nuked the project whoops

### CODE REVIEW

**Review by some-molasses — CHANGES_REQUESTED** [review]
let's move things _even more_ >:)

In particular, can we take the `data` folder out of the `server` folder and move it to the root?  I think `config` can stay, since it's more directly related to the server function, but there could also be an argument for moving it out of the code files and into the root as well. 

I'm also not certain I agree with putting all of the controllers into a `controllers` folder - it doesn't feel like the folder has a cohesive purpose.  Could we instead consider putting `controllers` subfolders within `api` and `routes`, to group these files by functional area rather than by file 'type'?

**Comment by ad-world** [comment]
To respond to the first point - although the data folder isn't really needed in the server folder, I think it deserves to be there since that's the only place those files are directly used. I think moving it out may be confusing since then it seems like those files can be used anywhere in the project (i.e the front end ts folder) which I don't think it something we want to do since we've set up api endpoints that the frontend can call to get this data. So yea pretty much although there's nothing stopping us from moving it out, we might lose some encapsulation of logic/sensible structure if we move it out. I would love to hear your thoughts though

**Comment by ad-world** [comment]
> Could we instead consider putting controllers subfolders within api and routes, to group these files by functional area rather than by file 'type'?

I like this much more than the current solution in this branch, but what do we do when we have a controller that's used in both the routes + api folders. I'm not sure if that ever will be a possibility, but in the case that it is how do you feel about instead putting two directories in the controllers folder (api and routes) where the current files can live in the folder they mostly function in, and newer controllers that have to be shared can be put in the root controllers directory? Would also love to hear thoughts on this.

**Comment by ad-world** [comment]
Btw if you're wondering how I'm doing this comments without my personal laptop, I just had to share I'm doing these at 7:21am on the GitHub phone app while otw to Toronto 😭😭😭😭

**Comment by some-molasses** [comment]
I understand your point with respect to the server folder, but I think it's not necessarily wrong to imply that the files can be accessed (assuming it's physically possible to reach them?).  

I'm trying to think ahead to when we need to be able to upload images and exams to the site - neither of these should go into our existing `data` folder of JSON files; that folder is currently set up specifically to deal with JSON and wouldn't take well to having images or PDF files included. In that case, we'll likely end up with two more 'data' folders, one for images and one for exam PDFs.  I think I'm primarily looking to have all of these in some centralized folder - whether or not it's in the server directory isn't necessarily relevant, so I'm okay with leaving it or moving it, although I think I'd prefer move given that the files will sometimes be directly sent to the frontend.

As for the controllers subfolders, I think that would work!

good luck with the toronto trip!  github mobile PR review is some real dedication 😤 😤 😤

**Comment by some-molasses** [comment]
how do I approve on mobile 😭

**Review by some-molasses — APPROVED** [review]

**Pull request merged**
